spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---

spring.config.activate.on-profile: dev

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: XHfjtEZQQA3FxkfaX7XJ8aJkrJfpbavR3BXrMpmNMGt*9QZrHtLLUVhNe4z-fXnGMQaUPtTtp2ZtD2bD4cefyVLKtcicRtRTF6_4
    url: jdbc:postgresql://192.168.0.24:5432/kapp?sslmode=disable
    username: supabase_admin

---

spring.config.activate.on-profile: prod

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: XHfjtEZQQA3FxkfaX7XJ8aJkrJfpbavR3BXrMpmNMGt*9QZrHtLLUVhNe4z-fXnGMQaUPtTtp2ZtD2bD4cefyVLKtcicRtRTF6_4
    url: jdbc:postgresql://192.168.0.24:5432/kapp?sslmode=disable
    username: supabase_admin
