package koreatech.kapp.persistence.user

import koreatech.kapp.domain.common.Email
import koreatech.kapp.domain.user.model.HashedPassword
import koreatech.kapp.domain.user.model.User
import org.jooq.DSLContext
import org.jooq.SQLDialect
import org.jooq.impl.DSL
import java.sql.Connection
import java.sql.DriverManager
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class DBUserRepositoryTest {

    private lateinit var connection: Connection
    private lateinit var dsl: DSLContext
    private lateinit var repository: DBUserRepository

    @BeforeTest
    fun setUp() {
        connection = DriverManager.getConnection(
            "jdbc:h2:mem:user_repo_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
        )
        dsl = DSL.using(connection, SQLDialect.H2)
        repository = DBUserRepository(dsl)

        dsl.execute(
            """
            create table "users" (
                "id" bigint generated by default as identity primary key,
                "email" varchar(255) not null unique,
                "password" varchar(255) not null,
                "name" varchar(100) not null,
                "student_employee_id" varchar(50) not null,
                "created_at" timestamp not null,
                "updated_at" timestamp not null
            )
            """.trimIndent()
        )
    }

    @AfterTest
    fun tearDown() {
        connection.close()
    }

    @Test
    fun `사용자 저장 후 이메일로 조회할 수 있다`() {
        val user = User.create(
            email = Email("repo@example.com"),
            password = HashedPassword("encoded-password"),
            name = "테스트유저",
            studentEmployeeId = "20240001"
        )

        val saved = repository.save(user)
        val loaded = repository.findByEmail(Email("repo@example.com"))

        assertNotNull(saved.id)
        assertNotNull(loaded)
        assertEquals(saved.id, loaded.id)
        assertTrue(repository.existsByEmail(Email("repo@example.com")))
    }
}
