package koreatech.kapp.persistence.meal

import koreatech.kapp.domain.meal.model.DiningTime
import org.jooq.DSLContext
import org.jooq.SQLDialect
import org.jooq.impl.DSL
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class DBMealRepositoryTest {

    private lateinit var connection: Connection
    private lateinit var dsl: DSLContext
    private lateinit var repository: DBMealRepository

    @BeforeTest
    fun setUp() {
        connection = DriverManager.getConnection(
            "jdbc:h2:mem:meal_repo_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
        )
        dsl = DSL.using(connection, SQLDialect.H2)
        repository = DBMealRepository(dsl)

        dsl.execute("""drop table if exists "meal_menu_items"""")
        dsl.execute("""drop table if exists "meals"""")

        dsl.execute(
            """
            create table "meals" (
                "id" bigint generated by default as identity primary key,
                "date" date not null,
                "dining_time" varchar(20) not null,
                "place" varchar(100) not null,
                "price" varchar(20) not null,
                "kcal" varchar(10) not null,
                "created_at" timestamp not null,
                "updated_at" timestamp not null
            )
            """.trimIndent()
        )

        dsl.execute(
            """
            create table "meal_menu_items" (
                "meal_id" bigint not null,
                "menu_item" varchar(200) not null
            )
            """.trimIndent()
        )
    }

    @AfterTest
    fun tearDown() {
        connection.close()
    }

    @Test
    fun `날짜 기준 식단을 조회할 수 있다`() {
        val targetDate = LocalDate.of(2026, 2, 14)
        val now = LocalDateTime.now()

        val mealId = dsl.insertInto(MealTable)
            .set(MealTable.DATE, targetDate)
            .set(MealTable.DINING_TIME, DiningTime.LUNCH.name)
            .set(MealTable.PLACE, "학생식당")
            .set(MealTable.PRICE, "5000")
            .set(MealTable.KCAL, "750")
            .set(MealTable.CREATED_AT, now)
            .set(MealTable.UPDATED_AT, now)
            .returningResult(MealTable.ID)
            .fetchOne()
            ?.value1()

        dsl.insertInto(MealMenuItemTable)
            .set(MealMenuItemTable.MEAL_ID, mealId)
            .set(MealMenuItemTable.MENU_ITEM, "김치찌개")
            .execute()

        dsl.insertInto(MealMenuItemTable)
            .set(MealMenuItemTable.MEAL_ID, mealId)
            .set(MealMenuItemTable.MENU_ITEM, "밥")
            .execute()

        val meals = repository.findByDate(targetDate)

        assertEquals(1, meals.size)
        assertEquals("학생식당", meals.first().place)
        assertEquals(2, meals.first().menu.items.size)
        assertTrue(meals.first().menu.items.contains("김치찌개"))
    }

    @Test
    fun `소문자 dining_time 값도 조회할 수 있다`() {
        val targetDate = LocalDate.of(2026, 2, 15)
        val now = LocalDateTime.now()

        val mealId = dsl.insertInto(MealTable)
            .set(MealTable.DATE, targetDate)
            .set(MealTable.DINING_TIME, "breakfast")
            .set(MealTable.PLACE, "복지관")
            .set(MealTable.PRICE, "4500")
            .set(MealTable.KCAL, "600")
            .set(MealTable.CREATED_AT, now)
            .set(MealTable.UPDATED_AT, now)
            .returningResult(MealTable.ID)
            .fetchOne()
            ?.value1()

        dsl.insertInto(MealMenuItemTable)
            .set(MealMenuItemTable.MEAL_ID, mealId)
            .set(MealMenuItemTable.MENU_ITEM, "계란찜")
            .execute()

        val meals = repository.findByDate(targetDate)

        assertEquals(1, meals.size)
        assertEquals(DiningTime.BREAKFAST, meals.first().diningTime)
    }
}
